"""Added new migration

Revision ID: 00eb3b0ca87b
Revises: 3d6e65f64dfa
Create Date: 2024-12-24 18:55:46.835307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00eb3b0ca87b'
down_revision: Union[str, None] = '3d6e65f64dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
